import { ZipArchive } from "archiver";
import { ProjectMemory, getMemoryValue, formatMemoryValue } from "./project-memory";
import { SKILL_CATALOG } from "./skill-catalog";
import { resolve3dAssets } from "./identity-3d";
import { getChosenLogoSvg } from "./identity-logo";
import { buildReportPdf } from "./pdf-export";

/* ── Types ──────────────────────────────────────────────────────────── */

export interface HandoffOptions {
  projectId: string;
  projectName: string;
  ideaContext: {
    title: string;
    description: string;
    problem: string;
    valueProposition: string;
    targetUser: string;
    monetization: string;
    businessModel: string;
  };
  phases: Array<{
    type: string;
    label: string;
    sortOrder: number;
    artifacts: Array<{ title: string; content: string; type: string }> | null;
    subStepArtifact: { type?: string; content?: string; options?: Array<{ value: string; label: string }> } | null;
    subStepChoice: string | null;
    subStep: string | null;
    /** Historial de sub-pasos (naming/voice/logo/visual) — JSON tolerante. */
    subStepHistory?: unknown;
    description: string | null;
    status: string;
  }>;
  memory: ProjectMemory | null;
  /** Skills the user selected (from project.skills). Each has id, name, description, icon, category, selected, etc. */
  selectedSkills?: Array<{
    id: string;
    name: string;
    description: string;
    icon: string;
    category: string;
    confidence?: number;
    reason?: string;
    recommended?: boolean;
    selected?: boolean;
    custom?: boolean;
  }> | null;
  /** Skills generated by the generate endpoint (from project.generatedSkills). Each has id, name, content. */
  generatedSkills?: Array<{ id: string; name: string; content: string }> | null;
}

/* ── Sanitisation ───────────────────────────────────────────────────── */

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "proyecto";
}

function sanitizeSkillFilename(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

/* ── Phase artifact helpers ─────────────────────────────────────────── */

interface PhaseAsset {
  phaseType: string;
  label: string;
  sortOrder: number;
  titles: string[];
  contents: string[];
}

function extractPhaseAssets(ctx: HandoffOptions): PhaseAsset[] {
  return ctx.phases
    .filter((p) => p.status === "COMPLETED" && p.artifacts && p.artifacts.length > 0)
    .map((p) => {
      const arts = p.artifacts!;
      return {
        phaseType: p.type,
        label: p.label,
        sortOrder: p.sortOrder,
        titles: arts.map((a) => a.title),
        contents: arts.map((a) => a.content),
      };
    });
}

/* ── Identidad (Fase 3): voz/tono, logo y assets 3d ─────────────────── */

type HistoryMap = Record<
  string,
  { choice?: string; artifact?: { content?: string } | null }
> | null;

function getIdentityPhase(ctx: HandoffOptions) {
  return (
    ctx.phases.find((p) => p.type === "IDENTITY" && p.status === "COMPLETED") ??
    null
  );
}

function getHistory(phase: { subStepHistory?: unknown } | null): HistoryMap {
  const h = phase?.subStepHistory;
  return h && typeof h === "object" ? (h as NonNullable<HistoryMap>) : null;
}

/** Documento 3.voz-y-tono.md a partir del sub-paso voice (excluye naming). */
function buildVoiceDoc(ctx: HandoffOptions): string | null {
  const phase = getIdentityPhase(ctx);
  const voice = getHistory(phase)?.voice;
  const content = voice?.artifact?.content?.trim();
  if (!content) return null;
  return [`# Voz y Tono — ${ctx.projectName}`, "", content].join("\n");
}

/** SVG del logotipo elegido en 3c (o null). */
function getChosenLogo(ctx: HandoffOptions): string | null {
  const phase = getIdentityPhase(ctx);
  const logo = getHistory(phase)?.logo;
  if (!logo) return null;
  return getChosenLogoSvg(logo.artifact?.content, logo.choice);
}

/** Assets 3d (maqueta con logo + guía de estilo) o null. */
function getThreeDAssets(ctx: HandoffOptions) {
  const phase = getIdentityPhase(ctx);
  if (!phase) return null;
  return resolve3dAssets(
    {
      subStep: phase.subStep,
      subStepChoice: phase.subStepChoice,
      subStepArtifact: phase.subStepArtifact,
      subStepHistory: phase.subStepHistory,
    },
    phase.subStepChoice,
    ctx.projectName
  );
}

/* ── AGENT.md builder ────────────────────────────────────────────────── */

function buildAgentMd(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const mTarget = getMemoryValue<string>(memory, "target");
  const mTone = getMemoryValue<string>(memory, "tone");
  const mChannels = getMemoryValue<string | string[]>(memory, "channels");
  const mPricing = getMemoryValue<string>(memory, "pricing");
  const mBusinessModel = getMemoryValue<string>(memory, "businessModel");
  const mCompetitors = getMemoryValue<string>(memory, "competitors");

  const assets = extractPhaseAssets(ctx);
  const phaseListing = assets
    .map((a) => `- **Fase ${a.sortOrder} — ${a.label}**: ✅ Completada`)
    .join("\n");

  const visualMeta = getThreeDAssets(ctx)?.meta ?? null;

  const memoryEntries = memory
    ? Object.entries(memory)
        .filter(([, e]) => e && e.value !== null && e.value !== undefined)
    : [];

  const memorySection = memoryEntries.length > 0
    ? memoryEntries
        .map(([k, e]) => `- **${k}:** ${formatMemoryValue(e!.value)} (fuente: ${e!.source === "user" ? "usuario" : `Fase ${e!.source}`})`)
        .join("\n")
    : "- Sin decisiones registradas.";

  // Build skills overview for agent
  const selectedSkills = ctx.selectedSkills?.filter(s => s.selected !== false) ?? [];
  const skillsOverview = selectedSkills.length > 0
    ? selectedSkills.map(s => `  - **${s.name}** (${s.category}): ${s.description}`).join("\n")
    : "  - Sin skills seleccionadas.";

  return [
    `# AGENT.md — ${projectName}`,
    "",
    "> Este archivo da contexto completo a cualquier agente de IA (Cursor, Cline, Copilot, Claude, etc.) sobre el proyecto.",
    "> Pónlo en la raíz del proyecto. Los agentes lo leerán automáticamente.",
    "",
    "---",
    "",
    "## 🎯 Proyecto",
    "",
    `- **Nombre:** ${projectName}`,
    `- **Descripción:** ${ideaContext.description}`,
    `- **Problema:** ${ideaContext.problem || "—"}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "—"}`,
    `- **Target:** ${mTarget || ideaContext.targetUser}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    `- **Modelo de negocio:** ${mBusinessModel || ideaContext.businessModel || "—"}`,
    "",
    "---",
    "",
    "## 🧠 Decisiones Tomadas",
    "",
    memorySection,
    "",
    "---",
    "",
    "## 📦 Fases Completadas",
    "",
    phaseListing,
    "",
    "---",
    "",
    "## 🛠️ Skills del Proyecto",
    "",
    skillsOverview,
    "",
    "Cada skill está en \`skills/<nombre>.md\` con instrucciones detalladas y contexto del proyecto.",
    "",
    "---",
    "",
    "## 🎨 Identidad Visual",
    "",
    visualMeta
      ? [
          `- **Color primario:** \`${visualMeta.primaryColor}\``,
          `- **Color secundario:** \`${visualMeta.secondaryColor}\``,
          `- **Tipografía titulares:** ${visualMeta.fontHeading}`,
          `- **Tipografía cuerpo:** ${visualMeta.fontBody}`,
          `- **Tono:** ${mTone || "Profesional y cercano"}`,
          "",
          "Detalle completo en `3d.guia-de-estilo.md`. Logotipo en `skills/3c-logos/logo.svg`",
          "y maqueta en `skills/3d-assets/index.html` (con el logotipo incrustado).",
        ].join("\n")
      : "- Voz y tono en `3.voz-y-tono.md`; estilo visual en `3d.guia-de-estilo.md`.",
    "",
    "---",
    "",
    "## 🗂️ Cómo leer este paquete",
    "",
    "Lee los `.md` numerados en orden (1 → 5). Cada uno corresponde a una fase del",
    "proceso de validación. Los assets técnicos (logotipos, maqueta y guía de estilo)",
    "están en `skills/`. El proceso de *naming* se omite a propósito: no aporta",
    "contexto útil para construir el producto.",
    "",
    "## 📋 Instrucciones para el Agente",
    "",
    "1. **Lee este archivo** antes de empezar cualquier tarea.",
    "2. **Lee los reportes de fase** numerados (`1.*.md` … `5.*.md`) para el contexto de negocio.",
    "3. **Respeta las decisiones** tomadas (target, tono, canales, etc.).",
    "4. **Usa español** para todo el contenido y copy.",
    "5. **Mantén coherencia** con la identidad visual (`3d.guia-de-estilo.md` + assets).",
    "6. **Consulta las skills** de marketing en `skills/*.md` cuando apliquen.",
    "",
    "---",
    "",
    `*Generado por BrewIdea Validator el ${new Date().toISOString().split("T")[0]}*`,
  ].join("\n");
}

/* ── README.md builder ───────────────────────────────────────────────── */

function buildReadme(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const safeName = sanitizeFilename(projectName);

  const mTarget = getMemoryValue<string>(memory, "target");
  const mTone = getMemoryValue<string>(memory, "tone");
  const mChannels = getMemoryValue<string | string[]>(memory, "channels");

  const assets = extractPhaseAssets(ctx);

  const selectedSkills = ctx.selectedSkills?.filter(s => s.selected !== false) ?? [];
  const skillRows = selectedSkills.length > 0
    ? selectedSkills.map(s => `| \`${sanitizeSkillFilename(s.name)}.md\` | ${s.name} | ${s.description} |`).join("\n")
    : "| _(sin skills seleccionadas)_ | | |";

  return [
    `# ${projectName}`,
    "",
    `> Proyecto validado y desarrollado con **BrewIdea Validator**.`,
    "",
    `**Fecha:** ${new Date().toISOString().split("T")[0]}`,
    "",
    "---",
    "",
    "## 📁 Estructura del Proyecto",
    "",
    "```",
    `${safeName}/`,
    `├── AGENT.md                   ← Contexto para agentes AI (leer primero)`,
    `├── README.md                  ← Este archivo`,
    `├── 1.analisis-de-mercado.md   ← Análisis de mercado y competencia`,
    `├── 2.viabilidad-economica.md  ← Modelo de negocio y viabilidad`,
    `├── 3.voz-y-tono.md            ← Personalidad de marca (voz y tono)`,
    `├── 3d.guia-de-estilo.md       ← Colores, fuentes y dirección visual`,
    `├── 4.estrategia-distribucion.md ← Canales y contenido`,
    `├── 5.roadmap.md               ← Plan de ejecución 30/60/90`,
    `└── skills/                    ← Assets técnicos + skills de marketing`,
    `    ├── 3c-logos/`,
    `    │   ├── logo.svg           ← Logotipo elegido`,
    `    │   └── logos-options.html ← Las 12 propuestas`,
    `    ├── 3d-assets/`,
    `    │   ├── index.html         ← Maqueta con el logotipo incrustado`,
    `    │   └── guia-estilos.pdf   ← Guía de estilo en PDF`,
    `    └── *.md                   ← Skills de marketing seleccionadas`,
    "```",
    "",
    "> El proceso de _naming_ se excluye a propósito del paquete.",
    "",
    "---",
    "",
    "## 🚀 Cómo Empezar",
    "",
    "### Con Cursor / Cline / Copilot",
    "1. Abre esta carpeta en VS Code",
    "2. Los agentes leerán `AGENT.md` automáticamente",
    "3. Para tareas específicas, referencia la skill correspondiente:",
    '   - "Usa `skills/landing-page.md` para construir la landing"',
    '   - "Usa `skills/contenido-editorial.md` para escribir posts"',
    "",
    "### Con ChatGPT / Claude",
    "Copia el contenido de la skill que necesites como prompt inicial.",
    "Para contexto completo, copia `AGENT.md`.",
    "",
    "---",
    "",
    "## 📋 Idea Original",
    "",
    `- **Título:** ${ideaContext.title}`,
    `- **Problema:** ${ideaContext.problem || "—"}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "—"}`,
    `- **Target:** ${mTarget || ideaContext.targetUser}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    "",
    "---",
    "",
    "## 🛠️ Skills Incluidas",
    "",
    "| Archivo | Skill | Descripción |",
    "|---------|-------|-------------|",
    skillRows,
    "",
    "---",
    "",
    `*Generado por BrewIdea Validator el ${new Date().toISOString().split("T")[0]}*`,
  ].join("\n");
}

/* ── Phase document builders (unchanged except improvements) ─────────── */

function buildMarketAnalysis(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const analysis = assets.find((a) => a.phaseType === "ANALYSIS");
  if (!analysis) return null;
  return [
    `# Análisis de Mercado — ${ctx.projectName}`,
    "",
    ...analysis.contents,
  ].join("\n");
}

/** 3d.guia-de-estilo.md — guía de estilo (colores, fuentes, dirección visual). */
function buildStyleGuideDoc(ctx: HandoffOptions): string | null {
  const assets = getThreeDAssets(ctx);
  if (!assets) return null;
  return assets.styleGuideMarkdown;
}

function buildDistributionStrategy(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const content = assets.find((a) => a.phaseType === "CONTENT");
  if (!content) return null;
  return [
    `# Estrategia de Distribución — ${ctx.projectName}`,
    "",
    "## Canales y plataformas",
    "",
    ...content.contents.map((c, i) => `### ${content.titles[i] || "Documento"}\n\n${c}`),
  ].join("\n");
}

function buildBusinessPlan(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const biz = assets.find((a) => a.phaseType === "BUSINESS");
  if (!biz) return null;
  return [
    `# Estrategia de Negocio — ${ctx.projectName}`,
    "",
    "## Lean Canvas · Modelo de Ingresos · Propuesta de Valor",
    "",
    ...biz.contents.map((c, i) => `### ${biz.titles[i] || "Documento"}\n\n${c}`),
  ].join("\n");
}

function buildRoadmap(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const exec = assets.find((a) => a.phaseType === "EXECUTION");
  if (!exec) return null;
  return [
    `# Roadmap — ${ctx.projectName}`,
    "",
    "## Plan de ejecución 30/60/90 y próximos pasos",
    "",
    ...exec.contents.map((c, i) => `### ${exec.titles[i] || "Documento"}\n\n${c}`),
  ].join("\n");
}

/* ── Skill document builders ─────────────────────────────────────────── */

function buildLandingPageSkill(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const mTarget = getMemoryValue<string>(memory, "target") || ideaContext.targetUser;
  const mTone = getMemoryValue<string>(memory, "tone") || "profesional y cercano";

  const visualMeta = getThreeDAssets(ctx)?.meta;
  const primaryColor = visualMeta?.primaryColor || "#1a1a2e";
  const secondaryColor = visualMeta?.secondaryColor || "#e94560";
  const fontHeading = visualMeta?.fontHeading || "Inter";
  const fontBody = visualMeta?.fontBody || "Inter";

  return [
    `# Landing Page — ${projectName}`,
    "",
    `> Skill para construir la landing page de **${projectName}**.`,
    "",
    "---",
    "",
    "## Contexto",
    "",
    `- **Proyecto:** ${projectName}`,
    `- **Target:** ${mTarget}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "No definida"}`,
    `- **Problema:** ${ideaContext.problem || "No definido"}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    `- **Modelo de negocio:** ${ideaContext.businessModel || "No especificado"}`,
    "",
    "---",
    "",
    "## Identidad Visual",
    "",
    `- **Color primario:** \`${primaryColor}\``,
    `- **Color secundario:** \`${secondaryColor}\``,
    `- **Tipografía headings:** ${fontHeading}`,
    `- **Tipografía body:** ${fontBody}`,
    `- **Tono:** ${mTone}`,
    "",
    "---",
    "",
    "## Instrucciones",
    "",
    "Genera una landing page completa, responsive y lista para producción.",
    "",
    "### Secciones obligatorias",
    "",
    "1. **Hero** — Título impactante + subtítulo + CTA principal",
    "2. **Problema** — El dolor que resuelve el producto",
    "3. **Solución** — Cómo lo resuelve",
    "4. **Features** — 3-6 funcionalidades clave con iconos",
    "5. **Social Proof** — Testimonios / logos",
    "6. **Pricing** — Tabla de precios (placeholder si no definido)",
    "7. **FAQ** — 5-8 preguntas frecuentes",
    "8. **CTA final** — Repite el CTA principal",
    "9. **Footer** — Links, legal, redes",
    "",
    "### Stack técnico",
    "",
    "- Next.js 14+ (App Router)",
    "- Tailwind CSS",
    "- Lucide React icons",
    "- Responsive mobile-first",
    "",
    "---",
    "",
    `_Generado por BrewIdea Validator_`,
  ].join("\n");
}

function buildContentEditorialSkill(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const mTarget = getMemoryValue<string>(memory, "target") || ideaContext.targetUser;
  const mTone = getMemoryValue<string>(memory, "tone") || "profesional y cercano";

  return [
    `# Contenido Editorial — ${projectName}`,
    "",
    `> Skill para escribir contenido de marketing para **${projectName}**.`,
    "",
    "---",
    "",
    "## Contexto",
    "",
    `- **Proyecto:** ${projectName}`,
    `- **Target:** ${mTarget}`,
    `- **Tono:** ${mTone}`,
    `- **Idioma:** Español`,
    "",
    "---",
    "",
    "## Formatos",
    "",
    "### Posts de redes sociales",
    "- Hook → Problema → Solución → CTA",
    "- Twitter/X: máx 280 chars",
    "- LinkedIn: 800-1200 chars, storytelling",
    "- Instagram: carrusel educativo o Reel",
    "",
    "### Email marketing",
    "- Subject: 40-50 chars, curiosidad o beneficio",
    "- Body: 150-300 palabras",
    "- CTA claro al final",
    "",
    "### Anuncios (ads)",
    "- Headline: 30 chars máx",
    "- Body: 90 chars máx",
    "- CTA accionable",
    "",
    "### Blog posts",
    "- 800-2000 palabras",
    "- SEO-friendly: H1, H2, H3, bullets",
    "- Incluir keywords del análisis de mercado",
    "",
    "---",
    "",
    `_Generado por BrewIdea Validator_`,
  ].join("\n");
}

function buildSocialMediaSkill(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const mTarget = getMemoryValue<string>(memory, "target") || ideaContext.targetUser;
  const mChannels = getMemoryValue<string | string[]>(memory, "channels");
  const mTone = getMemoryValue<string>(memory, "tone") || "profesional y cercano";

  const channelsList = mChannels
    ? (Array.isArray(mChannels) ? mChannels : [mChannels])
    : ["Twitter/X", "LinkedIn", "Instagram"];

  return [
    `# Social Media Strategy — ${projectName}`,
    "",
    `> Skill para la estrategia en redes sociales de **${projectName}**.`,
    "",
    "---",
    "",
    "## Objetivos",
    "",
    `- **Proyecto:** ${projectName}`,
    `- **Target:** ${mTarget}`,
    `- **Canales:** ${channelsList.join(", ")}`,
    `- **Tono:** ${mTone}`,
    "",
    "---",
    "",
    "## Calendario editorial (30 días)",
    "",
    "### Semana 1 — Awareness",
    "- D1-2: Presentación del proyecto",
    "- D3-4: Contenido educativo sobre el problema",
    "- D5-7: CTA a lista de espera",
    "",
    "### Semana 2 — Engagement",
    "- D8-10: Tutoriales / hilos",
    "- D11-12: Encuestas a la comunidad",
    "- D13-14: Colaboraciones",
    "",
    "### Semana 3 — Conversión",
    "- D15-17: Casos de uso",
    "- D18-19: Comparativas",
    "- D20-21: Oferta early bird",
    "",
    "### Semana 4 — Retención",
    "- D22-24: UGC y testimonios",
    "- D25-26: Roadmap / features",
    "- D27-30: Resumen + próximos pasos",
    "",
    "---",
    "",
    "## Métricas",
    "",
    "| Métrica | Mes 1 | Mes 3 |",
    "|---------|-------|-------|",
    "| Seguidores | +100 | +500 |",
    "| Engagement | >3% | >5% |",
    "| Clicks web | 200 | 1000 |",
    "",
    "---",
    "",
    `_Generado por BrewIdea Validator_`,
  ].join("\n");
}

function buildProjectHandoffSkill(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;

  const entries = memory
    ? Object.entries(memory)
        .filter(([, e]) => e && e.value !== null && e.value !== undefined)
    : [];

  const selectedSkills = ctx.selectedSkills?.filter(s => s.selected !== false) ?? [];
  const skillList = selectedSkills.length > 0
    ? selectedSkills.map(s => `  - **${s.name}** (\`skills/${sanitizeSkillFilename(s.name)}.md\`)`).join("\n")
    : "  - _(ninguna seleccionada)_";

  return [
    `# Project Handoff — ${projectName}`,
    "",
    `> Meta-skill: contexto completo de **${projectName}** para cualquier agente AI.`,
    "> Arrastra este archivo al chat de Cursor/Cline/Copilot para que tenga todo el contexto.",
    "",
    "---",
    "",
    "## Idea Original",
    "",
    `- **Nombre:** ${projectName}`,
    `- **Descripción:** ${ideaContext.description}`,
    `- **Problema:** ${ideaContext.problem || "—"}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "—"}`,
    `- **Target:** ${ideaContext.targetUser}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    `- **Modelo de negocio:** ${ideaContext.businessModel || "—"}`,
    "",
    "---",
    "",
    "## Decisiones del Proyecto",
    "",
    ...(entries.length > 0
      ? entries.map(
          ([k, e]) =>
            `- **${k}:** ${formatMemoryValue(e!.value)} (${e!.source === "user" ? "usuario" : `Fase ${e!.source}`})`
        )
      : ["- Sin decisiones registradas."]),
    "",
    "---",
    "",
    "## Skills Disponibles",
    "",
    skillList,
    "",
    "---",
    "",
    "## Cómo Usar",
    "",
    "1. Abre el proyecto en tu IDE",
    '2. Arrastra `AGENT.md` al chat del agente',
    "3. El agente tiene TODO el contexto del proyecto",
    "4. Para tareas específicas, referencia la skill:",
    '   - "Usa `skills/landing-page.md` para construir la landing"',
    '   - "Usa `skills/contenido-editorial.md` para escribir posts"',
    "",
    "---",
    "",
    `_Generado por BrewIdea Validator_`,
  ].join("\n");
}

/**
 * Build a skill file for any catalog skill that doesn't have a dedicated template.
 * Uses the skill catalog definition for context.
 */
function buildGenericSkill(ctx: HandoffOptions, skill: { id: string; name: string; description: string; icon: string; category: string }): string {
  const { projectName, ideaContext } = ctx;
  const catalogSkill = SKILL_CATALOG.find(s => s.id === skill.id);

  return [
    `# ${skill.name} — ${projectName}`,
    "",
    `> Skill de **${skill.category}** para **${projectName}**.`,
    "",
    "---",
    "",
    "## Contexto",
    "",
    `- **Proyecto:** ${projectName}`,
    `- **Target:** ${ideaContext.targetUser}`,
    `- **Modelo de negocio:** ${ideaContext.businessModel || "—"}`,
    `- **Descripción:** ${ideaContext.description}`,
    "",
    "---",
    "",
    "## Objetivo",
    "",
    skill.description,
    "",
    ...(catalogSkill ? [
      "",
      "## Criterios de Recomendación",
      "",
      ...catalogSkill.conditions.map(c => {
        switch (c.type) {
          case "always": return "- Siempre recomendada (base universal)";
          case "business_model_is": return `- Modelo de negocio: ${c.values.join(", ")}`;
          case "phase_artifact_contains": return `- Fase ${c.phaseType} contiene: ${c.keywords.join(", ")}`;
          case "has_channel_in_bullseye": return `- Canales en Bullseye: ${c.channelKeywords.join(", ")}`;
          default: return `- ${c.type}`;
        }
      }),
    ] : []),
    "",
    "---",
    "",
    "## Instrucciones",
    "",
    "1. Lee el contexto del proyecto en `AGENT.md`",
    "2. Aplica las decisiones tomadas (target, tono, canales, etc.)",
    "3. Genera el deliverable específico de esta skill",
    "4. Usa español para todo el contenido",
    "",
    "---",
    "",
    `_Generado por BrewIdea Validator_`,
  ].join("\n");
}

/* ── Main builder ───────────────────────────────────────────────────── */

/**
 * Genera un Buffer con el ZIP del handoff package.
 *
 * El ZIP ahora:
 * - Incluye AGENT.md con contexto completo para agentes AI
 * - Usa las skills seleccionadas por el usuario (no hardcodeadas)
 * - Tiene estructura de proyecto lista para VS Code
 * - Cada skill tiene un nombre de archivo descriptivo
 */
export async function buildHandoffZip(options: HandoffOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = new ZipArchive({ zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    archive.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on("error", (err: Error) => {
      reject(err);
    });

    const safeName = sanitizeFilename(options.projectName);
    const prefix = `${safeName}/`;

    const assets = extractPhaseAssets(options);

    // ── AGENT.md (context for AI agents — read first) ──
    archive.append(buildAgentMd(options), { name: `${prefix}AGENT.md` });

    // ── README.md ──
    archive.append(buildReadme(options), { name: `${prefix}README.md` });

    // ── Documentos de fase (markdown numerado, secuencial) ──
    // El proceso de NAMING se excluye a propósito (no aporta contexto útil
    // para agentes externos). Tampoco hay Brand Book consolidado.
    const marketAnalysis = buildMarketAnalysis(options, assets);
    if (marketAnalysis) {
      archive.append(marketAnalysis, { name: `${prefix}1.analisis-de-mercado.md` });
    }

    const businessPlan = buildBusinessPlan(options, assets);
    if (businessPlan) {
      archive.append(businessPlan, { name: `${prefix}2.viabilidad-economica.md` });
    }

    // 3.voz-y-tono.md — sub-paso voice (sin naming).
    const voiceDoc = buildVoiceDoc(options);
    if (voiceDoc) {
      archive.append(voiceDoc, { name: `${prefix}3.voz-y-tono.md` });
    }

    // 3d.guia-de-estilo.md — documentación de estilos (colores, fuentes).
    const styleGuideDoc = buildStyleGuideDoc(options);
    if (styleGuideDoc) {
      archive.append(styleGuideDoc, { name: `${prefix}3d.guia-de-estilo.md` });
    }

    const distStrategy = buildDistributionStrategy(options, assets);
    if (distStrategy) {
      archive.append(distStrategy, { name: `${prefix}4.estrategia-distribucion.md` });
    }

    const roadmap = buildRoadmap(options, assets);
    if (roadmap) {
      archive.append(roadmap, { name: `${prefix}5.roadmap.md` });
    }

    // ── skills/3c-logos/ y skills/3d-assets/ — assets técnicos de identidad ──
    const chosenLogo = getChosenLogo(options);
    if (chosenLogo) {
      archive.append(chosenLogo, { name: `${prefix}skills/3c-logos/logo.svg` });
    }
    const identityPhase = getIdentityPhase(options);
    const logoOptionsHtml = getHistory(identityPhase)?.logo?.artifact?.content;
    if (logoOptionsHtml) {
      archive.append(logoOptionsHtml, {
        name: `${prefix}skills/3c-logos/logos-options.html`,
      });
    }

    const threeD = getThreeDAssets(options);
    if (threeD) {
      archive.append(threeD.maquetaHtml, {
        name: `${prefix}skills/3d-assets/index.html`,
      });
      // Guía de estilo en PDF (servidor): documenta colores y fuentes. El
      // logotipo SVG va incrustado en index.html y como logo.svg.
      try {
        const pdf = buildReportPdf({
          title: `Guía de Estilo — ${options.projectName}`,
          content: threeD.styleGuideMarkdown,
          phaseType: "IDENTITY",
          projectName: options.projectName,
        });
        archive.append(pdf, { name: `${prefix}skills/3d-assets/guia-estilos.pdf` });
      } catch (err) {
        console.error("[handoff] no se pudo generar guia-estilos.pdf:", err);
      }
    }

    // ── Skills/ — skills de marketing seleccionadas por el usuario ──

    const selectedSkills = options.selectedSkills?.filter(s => s.selected !== false) ?? [];
    const generatedSkills = options.generatedSkills ?? [];

    // Map generated skills by id for content lookup
    const generatedMap = new Map<string, { id: string; name: string; content: string }>();
    for (const gs of generatedSkills) {
      generatedMap.set(gs.id, gs);
    }

    // Core skills that always appear (handoff + landing)
    const hasSkills = selectedSkills.length > 0 || generatedSkills.length > 0;

    if (hasSkills) {
      // Build a skill file for each selected skill
      for (const skill of selectedSkills) {
        const filename = sanitizeSkillFilename(skill.name) + ".md";

        // Try to find a generated content first
        const generated = generatedMap.get(skill.id);
        if (generated && generated.content) {
          archive.append(generated.content, { name: `${prefix}skills/${filename}` });
          continue;
        }

        // Then try dedicated builders
        switch (skill.id) {
          case "web-creator":
            archive.append(buildLandingPageSkill(options), { name: `${prefix}skills/${filename}` });
            break;
          case "project-handoff":
            archive.append(buildProjectHandoffSkill(options), { name: `${prefix}skills/${filename}` });
            break;
          case "contenido-publicaciones":
            archive.append(buildContentEditorialSkill(options), { name: `${prefix}skills/${filename}` });
            break;
          case "social-media":
            archive.append(buildSocialMediaSkill(options), { name: `${prefix}skills/${filename}` });
            break;
          case "seo-aso":
            // SEO skill doesn't have a dedicated builder yet, use generic
            archive.append(buildGenericSkill(options, skill), { name: `${prefix}skills/${filename}` });
            break;
          default:
            // Generic skill file from catalog definition
            archive.append(buildGenericSkill(options, skill), { name: `${prefix}skills/${filename}` });
            break;
        }
      }
    } else {
      // No skills selected/generated (user skipped, or none matched). Include
      // only the project-handoff meta-context skill so the package is still
      // usable — we do NOT ship skills the user didn't ask for (e.g. landing).
      archive.append(buildProjectHandoffSkill(options), { name: `${prefix}skills/project-handoff.md` });
    }

    // Ensure the project-handoff meta-context skill is present exactly once.
    // When skills were selected but project-handoff wasn't among them, add it.
    // (When it WAS selected, the loop above already wrote it; when there were
    // no skills, the else branch above already wrote it.)
    if (hasSkills && !selectedSkills.some(s => s.id === "project-handoff")) {
      archive.append(buildProjectHandoffSkill(options), { name: `${prefix}skills/project-handoff.md` });
    }

    void archive.finalize();
  });
}