import { ZipArchive } from "archiver";
import { ProjectMemory, getMemoryValue, formatMemoryValue, memoryKeyLabels } from "./project-memory";
import { resolve3dAssets } from "./identity-3d";
import { getChosenLogoSvg } from "./identity-logo";
import { buildReportPdf } from "./pdf-export";
import { stripProcessSections } from "./phase-context-parser";
import { buildProjectContext } from "./skill-context";
import { buildSkillMarkdown } from "./skill-templates";

/* ── Types ──────────────────────────────────────────────────────────── */

export interface HandoffOptions {
  projectId: string;
  projectName: string;
  ideaContext: {
    title: string;
    description: string;
    problem: string;
    valueProposition: string;
    targetUser: string;
    monetization: string;
    businessModel: string;
  };
  phases: Array<{
    type: string;
    label: string;
    sortOrder: number;
    artifacts: Array<{ title: string; content: string; type: string }> | null;
    subStepArtifact: { type?: string; content?: string; options?: Array<{ value: string; label: string }> } | null;
    subStepChoice: string | null;
    subStep: string | null;
    /** Historial de sub-pasos (naming/voice/logo/visual) — JSON tolerante. */
    subStepHistory?: unknown;
    description: string | null;
    status: string;
  }>;
  memory: ProjectMemory | null;
  /** Skills the user selected (from project.skills). Each has id, name, description, icon, category, selected, etc. */
  selectedSkills?: Array<{
    id: string;
    name: string;
    description: string;
    icon: string;
    category: string;
    confidence?: number;
    reason?: string;
    recommended?: boolean;
    selected?: boolean;
    custom?: boolean;
  }> | null;
  /** Skills generated by the generate endpoint (from project.generatedSkills). Each has id, name, content. */
  generatedSkills?: Array<{ id: string; name: string; content: string }> | null;
}

/* ── Sanitisation ───────────────────────────────────────────────────── */

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "proyecto";
}

function sanitizeSkillFilename(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

/* ── Phase artifact helpers ─────────────────────────────────────────── */

interface PhaseAsset {
  phaseType: string;
  label: string;
  sortOrder: number;
  titles: string[];
  contents: string[];
}

function extractPhaseAssets(ctx: HandoffOptions): PhaseAsset[] {
  return ctx.phases
    .filter((p) => p.status === "COMPLETED" && p.artifacts && p.artifacts.length > 0)
    .map((p) => {
      const arts = p.artifacts!;
      return {
        phaseType: p.type,
        label: p.label,
        sortOrder: p.sortOrder,
        titles: arts.map((a) => a.title),
        contents: arts.map((a) => a.content),
      };
    });
}

/* ── Identidad (Fase 3): voz/tono, logo y assets 3d ─────────────────── */

type HistoryMap = Record<
  string,
  { choice?: string; artifact?: { content?: string } | null }
> | null;

function getIdentityPhase(ctx: HandoffOptions) {
  return (
    ctx.phases.find((p) => p.type === "IDENTITY" && p.status === "COMPLETED") ??
    null
  );
}

function getHistory(phase: { subStepHistory?: unknown } | null): HistoryMap {
  const h = phase?.subStepHistory;
  return h && typeof h === "object" ? (h as NonNullable<HistoryMap>) : null;
}

/** Documento 3.voz-y-tono.md a partir del sub-paso voice (excluye naming). */
function buildVoiceDoc(ctx: HandoffOptions): string | null {
  const phase = getIdentityPhase(ctx);
  const voice = getHistory(phase)?.voice;
  const content = voice?.artifact?.content?.trim();
  if (!content) return null;
  return [`# Voz y Tono — ${ctx.projectName}`, "", content].join("\n");
}

/** SVG del logotipo elegido en 3c (o null). */
function getChosenLogo(ctx: HandoffOptions): string | null {
  const phase = getIdentityPhase(ctx);
  const logo = getHistory(phase)?.logo;
  if (!logo) return null;
  return getChosenLogoSvg(logo.artifact?.content, logo.choice);
}

/** Assets 3d (maqueta con logo + guía de estilo) o null. */
function getThreeDAssets(ctx: HandoffOptions) {
  const phase = getIdentityPhase(ctx);
  if (!phase) return null;
  return resolve3dAssets(
    {
      subStep: phase.subStep,
      subStepChoice: phase.subStepChoice,
      subStepArtifact: phase.subStepArtifact,
      subStepHistory: phase.subStepHistory,
    },
    phase.subStepChoice,
    ctx.projectName
  );
}

/* ── AGENT.md builder ────────────────────────────────────────────────── */

function buildAgentMd(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const mTarget = getMemoryValue<string>(memory, "target");
  const mTone = getMemoryValue<string>(memory, "tone");
  const mChannels = getMemoryValue<string | string[]>(memory, "channels");
  const mPricing = getMemoryValue<string>(memory, "pricing");
  const mBusinessModel = getMemoryValue<string>(memory, "businessModel");
  const mCompetitors = getMemoryValue<string>(memory, "competitors");

  const assets = extractPhaseAssets(ctx);
  const phaseListing = assets
    .map((a) => `- **Fase ${a.sortOrder} — ${a.label}**: ✅ Completada`)
    .join("\n");

  const visualMeta = getThreeDAssets(ctx)?.meta ?? null;

  const memoryEntries = memory
    ? Object.entries(memory)
        .filter(([, e]) => e && e.value !== null && e.value !== undefined)
    : [];

  const memorySection = memoryEntries.length > 0
    ? memoryEntries
        .map(([k, e]) => {
          const label = memoryKeyLabels[k] ?? k;
          const src = e!.source === "user" ? "usuario" : `Fase ${e!.source}`;
          const why = e!.rationale ? ` — _${e!.rationale}_` : "";
          return `- **${label}:** ${formatMemoryValue(e!.value)} (fuente: ${src})${why}`;
        })
        .join("\n")
    : "- Sin decisiones registradas.";

  // Build skills overview for agent
  const selectedSkills = ctx.selectedSkills?.filter(s => s.selected !== false) ?? [];
  const skillsOverview = selectedSkills.length > 0
    ? selectedSkills.map(s => `  - **${s.name}** (${s.category}): ${s.description}`).join("\n")
    : "  - Sin skills seleccionadas.";

  return [
    `# AGENT.md — ${projectName}`,
    "",
    "> Este archivo da contexto completo a cualquier agente de IA (Cursor, Cline, Copilot, Claude, etc.) sobre el proyecto.",
    "> Pónlo en la raíz del proyecto. Los agentes lo leerán automáticamente.",
    "",
    "---",
    "",
    "## 🎯 Proyecto",
    "",
    `- **Nombre:** ${projectName}`,
    `- **Descripción:** ${ideaContext.description}`,
    `- **Problema:** ${ideaContext.problem || "—"}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "—"}`,
    `- **Target:** ${mTarget || ideaContext.targetUser}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    `- **Modelo de negocio:** ${mBusinessModel || ideaContext.businessModel || "—"}`,
    "",
    "---",
    "",
    "## 🧠 Decisiones Tomadas",
    "",
    memorySection,
    "",
    "---",
    "",
    "## 📦 Fases Completadas",
    "",
    phaseListing,
    "",
    "---",
    "",
    "## 🛠️ Skills del Proyecto",
    "",
    skillsOverview,
    "",
    "Cada skill está en \`skills/<nombre>.md\` con instrucciones detalladas y contexto del proyecto.",
    "",
    "---",
    "",
    "## 🎨 Identidad Visual",
    "",
    visualMeta
      ? [
          `- **Color primario:** \`${visualMeta.primaryColor}\``,
          `- **Color secundario:** \`${visualMeta.secondaryColor}\``,
          `- **Tipografía titulares:** ${visualMeta.fontHeading}`,
          `- **Tipografía cuerpo:** ${visualMeta.fontBody}`,
          `- **Tono:** ${mTone || "Profesional y cercano"}`,
          "",
          "Detalle completo en `contexto/3d.guia-de-estilo.md`. Logotipo en `assets/logo.svg`",
          "y template de componentes en `assets/template.html` (con el logotipo incrustado).",
        ].join("\n")
      : "- Voz y tono en `contexto/3.voz-y-tono.md`; estilo visual en `contexto/3d.guia-de-estilo.md`.",
    "",
    "---",
    "",
    "## 🗂️ Mapa del paquete (consulta puntual)",
    "",
    "**Este archivo (`AGENT.md`) es el eje central**: contiene el resumen y las decisiones",
    "del proyecto. Empieza siempre por aquí. NO leas todo el contexto por defecto: usa el",
    "mapa de abajo para ir SOLO al archivo que necesites para la tarea concreta.",
    "",
    "- `contexto/1.analisis-de-mercado.md` — competencia, tendencias y oportunidad.",
    "- `contexto/2.viabilidad-economica.md` — costes, precios y unit economics.",
    "- `contexto/3.voz-y-tono.md` — cómo comunica la marca.",
    "- `contexto/3d.guia-de-estilo.md` — paleta, tipografía y componentes.",
    "- `contexto/4.estrategia-distribucion.md` — canales y plan de contenidos.",
    "- `contexto/5.roadmap.md` — fases y prioridades de ejecución.",
    "- `assets/` — logotipo (`logo.svg`, 1:1), template de componentes (`template.html`) y guía en PDF.",
    "- `skills/*.md` — guías accionables de marketing/desarrollo; cada una indica qué consultar.",
    "",
    "## 📋 Instrucciones para el Agente",
    "",
    "1. **Empieza por este archivo** (`AGENT.md`) — es el eje central de contexto.",
    "2. **Busca solo lo necesario**: ve al archivo del mapa que cubra la tarea actual; no leas todo.",
    "3. **Respeta las decisiones** tomadas (target, tono, canales, etc.).",
    "4. **Usa español** para todo el contenido y copy.",
    "5. **Mantén coherencia** con la identidad visual (`contexto/3d.guia-de-estilo.md` + `assets/`).",
    "6. **Consulta las skills** de `skills/*.md` cuando apliquen a la tarea.",
    "",
    "---",
    "",
    `*Generado por BrewIdea Validator el ${new Date().toISOString().split("T")[0]}*`,
  ].join("\n");
}

/* ── README.md builder ───────────────────────────────────────────────── */

function buildReadme(ctx: HandoffOptions): string {
  const { projectName, ideaContext, memory } = ctx;
  const safeName = sanitizeFilename(projectName);

  const mTarget = getMemoryValue<string>(memory, "target");
  const mTone = getMemoryValue<string>(memory, "tone");
  const mChannels = getMemoryValue<string | string[]>(memory, "channels");

  const assets = extractPhaseAssets(ctx);

  const selectedSkills = ctx.selectedSkills?.filter(s => s.selected !== false) ?? [];
  const skillRows = selectedSkills.length > 0
    ? selectedSkills.map(s => `| \`${sanitizeSkillFilename(s.name)}.md\` | ${s.name} | ${s.description} |`).join("\n")
    : "| _(sin skills seleccionadas)_ | | |";

  return [
    `# ${projectName}`,
    "",
    `> Proyecto validado y desarrollado con **BrewIdea Validator**.`,
    "",
    `**Fecha:** ${new Date().toISOString().split("T")[0]}`,
    "",
    "---",
    "",
    "## Estructura del Paquete",
    "",
    "```",
    `${safeName}/`,
    `├── AGENT.md                       <- Contexto para agentes IA (leer primero)`,
    `├── README.md                      <- Este archivo`,
    `├── contexto/                      <- Documentacion del proyecto (leer en orden)`,
    `│   ├── 1.analisis-de-mercado.md`,
    `│   ├── 2.viabilidad-economica.md`,
    `│   ├── 3.voz-y-tono.md`,
    `│   ├── 3d.guia-de-estilo.md`,
    `│   ├── 4.estrategia-distribucion.md`,
    `│   └── 5.roadmap.md`,
    `├── assets/                        <- Identidad visual`,
    `│   ├── logo.svg                   <- Logotipo elegido`,
    `│   ├── template.html              <- Template de componentes con el logotipo incrustado`,
    `│   └── guia-estilos.pdf           <- Guia de estilo en PDF`,
    `└── skills/                        <- Guias accionables (referencian ../contexto y ../assets)`,
    `    └── *.md`,
    "```",
    "",
    "> El proceso de naming se excluye a proposito del paquete.",
    "",
    "---",
    "",
    "## 🚀 Cómo Empezar",
    "",
    "### Con Cursor / Cline / Copilot",
    "1. Abre esta carpeta en VS Code",
    "2. Los agentes leerán `AGENT.md` automáticamente",
    "3. Para tareas específicas, referencia la skill correspondiente:",
    '   - "Usa `skills/landing-page.md` para construir la landing"',
    '   - "Usa `skills/contenido-editorial.md` para escribir posts"',
    "",
    "### Con ChatGPT / Claude",
    "Copia el contenido de la skill que necesites como prompt inicial.",
    "Para contexto completo, copia `AGENT.md`.",
    "",
    "---",
    "",
    "## 📋 Idea Original",
    "",
    `- **Título:** ${ideaContext.title}`,
    `- **Problema:** ${ideaContext.problem || "—"}`,
    `- **Propuesta de valor:** ${ideaContext.valueProposition || "—"}`,
    `- **Target:** ${mTarget || ideaContext.targetUser}`,
    `- **Monetización:** ${ideaContext.monetization}`,
    "",
    "---",
    "",
    "## 🛠️ Skills Incluidas",
    "",
    "| Archivo | Skill | Descripción |",
    "|---------|-------|-------------|",
    skillRows,
    "",
    "---",
    "",
    `*Generado por BrewIdea Validator el ${new Date().toISOString().split("T")[0]}*`,
  ].join("\n");
}

/* ── Phase document builders (unchanged except improvements) ─────────── */

function buildMarketAnalysis(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const analysis = assets.find((a) => a.phaseType === "ANALYSIS");
  if (!analysis) return null;
  return [
    `# Análisis de Mercado — ${ctx.projectName}`,
    "",
    ...analysis.contents.map((c) => stripProcessSections(c)),
  ].join("\n");
}

/** 3d.guia-de-estilo.md — guía de estilo (colores, fuentes, dirección visual). */
function buildStyleGuideDoc(ctx: HandoffOptions): string | null {
  const assets = getThreeDAssets(ctx);
  if (!assets) return null;
  return assets.styleGuideMarkdown;
}

function buildDistributionStrategy(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const content = assets.find((a) => a.phaseType === "CONTENT");
  if (!content) return null;
  return [
    `# Estrategia de Distribución — ${ctx.projectName}`,
    "",
    "## Canales y plataformas",
    "",
    ...content.contents.map((c, i) => `### ${content.titles[i] || "Documento"}\n\n${stripProcessSections(c)}`),
  ].join("\n");
}

function buildBusinessPlan(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const biz = assets.find((a) => a.phaseType === "BUSINESS");
  if (!biz) return null;
  return [
    `# Estrategia de Negocio — ${ctx.projectName}`,
    "",
    "## Lean Canvas · Modelo de Ingresos · Propuesta de Valor",
    "",
    ...biz.contents.map((c, i) => `### ${biz.titles[i] || "Documento"}\n\n${stripProcessSections(c)}`),
  ].join("\n");
}

function buildRoadmap(ctx: HandoffOptions, assets: PhaseAsset[]): string | null {
  const exec = assets.find((a) => a.phaseType === "EXECUTION");
  if (!exec) return null;
  return [
    `# Roadmap — ${ctx.projectName}`,
    "",
    "## Plan de ejecución 30/60/90 y próximos pasos",
    "",
    ...exec.contents.map((c, i) => `### ${exec.titles[i] || "Documento"}\n\n${c}`),
  ].join("\n");
}

/* ── Main builder ───────────────────────────────────────────────────── */

/**
 * Genera un Buffer con el ZIP del handoff package.
 *
 * El ZIP ahora:
 * - Incluye AGENT.md con contexto completo para agentes AI
 * - Usa las skills seleccionadas por el usuario (no hardcodeadas)
 * - Tiene estructura de proyecto lista para VS Code
 * - Cada skill tiene un nombre de archivo descriptivo
 */
export async function buildHandoffZip(options: HandoffOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = new ZipArchive({ zlib: { level: 9 } });
    const chunks: Buffer[] = [];

    archive.on("data", (chunk: Buffer) => {
      chunks.push(chunk);
    });

    archive.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    archive.on("error", (err: Error) => {
      reject(err);
    });

    const safeName = sanitizeFilename(options.projectName);
    const prefix = `${safeName}/`;

    const assets = extractPhaseAssets(options);

    // ── AGENT.md (context for AI agents — read first) ──
    archive.append(buildAgentMd(options), { name: `${prefix}AGENT.md` });

    // ── README.md ──
    archive.append(buildReadme(options), { name: `${prefix}README.md` });

    // ── Documentos de fase (markdown numerado, secuencial) ──
    // El proceso de NAMING se excluye a propósito (no aporta contexto útil
    // para agentes externos). Tampoco hay Brand Book consolidado.
    const marketAnalysis = buildMarketAnalysis(options, assets);
    if (marketAnalysis) {
      archive.append(marketAnalysis, { name: `${prefix}contexto/1.analisis-de-mercado.md` });
    }

    const businessPlan = buildBusinessPlan(options, assets);
    if (businessPlan) {
      archive.append(businessPlan, { name: `${prefix}contexto/2.viabilidad-economica.md` });
    }

    // 3.voz-y-tono.md — sub-paso voice (sin naming).
    const voiceDoc = buildVoiceDoc(options);
    if (voiceDoc) {
      archive.append(voiceDoc, { name: `${prefix}contexto/3.voz-y-tono.md` });
    }

    // 3d.guia-de-estilo.md — documentación de estilos (colores, fuentes).
    const styleGuideDoc = buildStyleGuideDoc(options);
    if (styleGuideDoc) {
      archive.append(styleGuideDoc, { name: `${prefix}contexto/3d.guia-de-estilo.md` });
    }

    const distStrategy = buildDistributionStrategy(options, assets);
    if (distStrategy) {
      archive.append(distStrategy, { name: `${prefix}contexto/4.estrategia-distribucion.md` });
    }

    const roadmap = buildRoadmap(options, assets);
    if (roadmap) {
      archive.append(roadmap, { name: `${prefix}contexto/5.roadmap.md` });
    }

    // ── assets/ — logotipo elegido + maqueta + guía de estilo en PDF ──
    // Solo el logotipo ELEGIDO (las 12 propuestas no aportan al entregable).
    const chosenLogo = getChosenLogo(options);
    if (chosenLogo) {
      archive.append(chosenLogo, { name: `${prefix}assets/logo.svg` });
    }

    const threeD = getThreeDAssets(options);
    if (threeD) {
      archive.append(threeD.maquetaHtml, {
        name: `${prefix}assets/template.html`,
      });
      // Guía de estilo en PDF (servidor): documenta colores y fuentes. El
      // logotipo SVG va incrustado en template.html y como logo.svg.
      try {
        const pdf = buildReportPdf({
          title: `Guia de Estilo - ${options.projectName}`,
          content: threeD.styleGuideMarkdown,
          phaseType: "IDENTITY",
          projectName: options.projectName,
        });
        archive.append(pdf, { name: `${prefix}assets/guia-estilos.pdf` });
      } catch (err) {
        console.error("[handoff] no se pudo generar guia-estilos.pdf:", err);
      }
    }

    // ── Skills/ — skills de marketing seleccionadas por el usuario ──

    const selectedSkills = options.selectedSkills?.filter(s => s.selected !== false) ?? [];
    const generatedSkills = options.generatedSkills ?? [];

    // Map generated skills by id for content lookup
    const generatedMap = new Map<string, { id: string; name: string; content: string }>();
    for (const gs of generatedSkills) {
      generatedMap.set(gs.id, gs);
    }

    // Contexto del proyecto para el generador determinista (única fuente de
    // verdad, compartida con el endpoint de generación). Solo se usa como
    // FALLBACK cuando una skill seleccionada no tiene contenido ya generado.
    const ctx = buildProjectContext({
      name: options.projectName,
      description: options.ideaContext.description,
      idea: {
        targetUser: options.ideaContext.targetUser,
        valueProposition: options.ideaContext.valueProposition,
        problem: options.ideaContext.problem,
        monetization: options.ideaContext.monetization,
        businessModel: options.ideaContext.businessModel,
      },
      phases: options.phases.map((p) => ({ label: p.label, type: p.type, status: p.status })),
      memory: options.memory,
    });

    // Core skills that always appear (handoff + landing)
    const hasSkills = selectedSkills.length > 0 || generatedSkills.length > 0;

    if (hasSkills) {
      // Build a skill file for each selected skill
      for (const skill of selectedSkills) {
        const filename = sanitizeSkillFilename(skill.name) + ".md";

        // Prefer the content already generated in the app (what the user sees).
        const generated = generatedMap.get(skill.id);
        if (generated && generated.content) {
          archive.append(generated.content, { name: `${prefix}skills/${filename}` });
          continue;
        }

        // Fallback: generate deterministically with the SAME builder as the app.
        archive.append(buildSkillMarkdown(skill.id, ctx), { name: `${prefix}skills/${filename}` });
      }
    } else {
      // No skills selected/generated (user skipped, or none matched). Include
      // only the project-handoff meta-context skill so the package is still
      // usable — we do NOT ship skills the user didn't ask for (e.g. landing).
      archive.append(buildSkillMarkdown("project-handoff", ctx), {
        name: `${prefix}skills/project-handoff.md`,
      });
    }

    // Ensure the project-handoff meta-context skill is present exactly once.
    // When skills were selected but project-handoff wasn't among them, add it.
    // (When it WAS selected, the loop above already wrote it; when there were
    // no skills, the else branch above already wrote it.)
    if (hasSkills && !selectedSkills.some(s => s.id === "project-handoff")) {
      archive.append(buildSkillMarkdown("project-handoff", ctx), {
        name: `${prefix}skills/project-handoff.md`,
      });
    }

    void archive.finalize();
  });
}