import type { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";

/**
 * Rename propagation — refactor IDENTITY Phase 2.
 *
 * When a user confirms a new name in the IDENTITY `naming` sub-step, we
 * update `idea.title` and `project.name`. But the name also appears in
 * artifacts that were generated by previous phases (Validation, Market
 * Analysis, etc.) — those are stored as JSON in `ProjectPhase.artifacts`
 * and `subStepArtifact`, and as markdown in `Report.content`.
 *
 * If we don't propagate the rename, the user sees "MiApp" in 14 places
 * across reports that supposedly describe "TuApp". This helper walks all
 * those places, applies a case-insensitive word-boundary regex replace,
 * and persists the changes atomically inside a single transaction.
 *
 * Important design choices:
 *  - No LLM. Pure regex, deterministic, fast.
 *  - Best-effort: only replaces if `oldName.length >= 2` (avoids false
 *    positives with single letters like "A").
 *  - Never touches `Job.input` / `Job.output` (immutable bridge logs).
 *  - Whole operation is wrapped in a `prisma.$transaction(async (tx) => …)`
 *    so a mid-flight failure rolls everything back.
 */

export interface OccurrenceLocation {
  kind: string;
  id: string;
  count: number;
  title: string;
}

export interface RenameStats {
  ideaTitleChanged: boolean;
  projectNameChanged: boolean;
  artifactsUpdated: number;
  reportsUpdated: number;
  totalReplacements: number;
  // Per-location breakdown for UI feedback
  occurrencesByLocation: OccurrenceLocation[];
}

interface PropagateParams {
  ideaId: string;
  projectId: string;
  oldName: string;
  newName: string;
}

/**
 * Escapes characters that have special meaning in a JavaScript regex.
 * Used to safely interpolate the user-supplied `oldName` into a
 * `RegExp`. Without escaping, a name like "App.io" would crash the
 * regex compiler.
 */
function escapeRegex(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Counts and replaces all whole-word, case-insensitive occurrences of
 * `pattern` in a string with `replacement`. Returns the new string and
 * the number of replacements made.
 */
function replaceAllWith(
  input: string,
  pattern: string,
  replacement: string
): { value: string; count: number } {
  if (!input || !pattern || pattern.length < 2) {
    return { value: input, count: 0 };
  }
  const re = new RegExp(`\\b${escapeRegex(pattern)}\\b`, "gi");
  let count = 0;
  const value = input.replace(re, () => {
    count += 1;
    return replacement;
  });
  return { value, count };
}

/**
 * Deep-traverses a JSON-serializable value and, for every string leaf,
 * runs `replaceAllWith` against `oldName → newName`. Returns a new value
 * (the input is not mutated) plus the total number of replacements
 * made.
 *
 * Safe to use with our payload types: artifacts/questions/subStepArtifact
 * are plain JSON (strings, numbers, arrays, plain objects), so the
 * `JSON.parse(JSON.stringify(value))` deep-clone is sufficient.
 */
function deepReplaceInJson(
  value: unknown,
  oldName: string,
  newName: string
): { value: unknown; count: number } {
  if (oldName.length < 2) return { value, count: 0 };
  let count = 0;
  function walk(node: unknown): unknown {
    if (typeof node === "string") {
      const { value: v, count: c } = replaceAllWith(node, oldName, newName);
      count += c;
      return v;
    }
    if (Array.isArray(node)) {
      return node.map(walk);
    }
    if (node && typeof node === "object") {
      const out: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(node)) {
        out[k] = walk(v);
      }
      return out;
    }
    return node;
  }
  const cloned = walk(value);
  return { value: cloned, count };
}

/**
 * Same traversal as `deepReplaceInJson` but only counts, doesn't
 * mutate. Used by `previewRename` to estimate impact without touching
 * the database.
 */
function deepCountInJson(value: unknown, oldName: string): number {
  if (oldName.length < 2) return 0;
  const re = new RegExp(`\\b${escapeRegex(oldName)}\\b`, "gi");
  function countInString(s: string): number {
    let c = 0;
    s.replace(re, () => {
      c += 1;
      return s;
    });
    return c;
  }
  function walk(node: unknown): number {
    if (typeof node === "string") return countInString(node);
    if (Array.isArray(node)) {
      let total = 0;
      for (const item of node) total += walk(item);
      return total;
    }
    if (node && typeof node === "object") {
      let total = 0;
      for (const v of Object.values(node)) total += walk(v);
      return total;
    }
    return 0;
  }
  return walk(value);
}

/**
 * Applies best-effort rename of the old name to the new name across:
 *   - Idea.title / description / problem / valueProposition
 *   - Project.name / description
 *   - ProjectPhase.artifacts / questions / subStepArtifact (per phase)
 *   - Report.title / content / scorecard
 *
 * Returns counters for UI feedback.
 *
 * The whole operation is a single interactive Prisma transaction
 * (`prisma.$transaction(async (tx) => …)`) — if anything throws,
 * nothing is persisted.
 */
export async function propagateRename(
  params: PropagateParams
): Promise<RenameStats> {
  const { ideaId, projectId, oldName, newName } = params;
  const cleanOld = oldName.trim();
  const cleanNew = newName.trim();

  const stats: RenameStats = {
    ideaTitleChanged: false,
    projectNameChanged: false,
    artifactsUpdated: 0,
    reportsUpdated: 0,
    totalReplacements: 0,
    occurrencesByLocation: [],
  };

  if (!cleanOld || !cleanNew) return stats;
  if (cleanOld.toLowerCase() === cleanNew.toLowerCase()) return stats;
  if (cleanOld.length < 2) return stats;

  // Run the full propagation in a single interactive transaction so
  // a partial failure rolls everything back.
  await prisma.$transaction(async (tx) => {
    // 1) Idea
    const currentIdea = await tx.idea.findUnique({
      where: { id: ideaId },
      select: {
        title: true,
        description: true,
        problem: true,
        valueProposition: true,
      },
    });
    if (currentIdea) {
      const newTitle = cleanNew;
      const newDesc = replaceAllWith(
        currentIdea.description,
        cleanOld,
        cleanNew
      );
      const newProblem =
        currentIdea.problem == null
          ? { value: currentIdea.problem, count: 0 }
          : replaceAllWith(currentIdea.problem, cleanOld, cleanNew);
      const newValueProp =
        currentIdea.valueProposition == null
          ? { value: currentIdea.valueProposition, count: 0 }
          : replaceAllWith(
              currentIdea.valueProposition,
              cleanOld,
              cleanNew
            );

      const ideaReplacements =
        (newTitle !== currentIdea.title ? 1 : 0) +
        newDesc.count +
        newProblem.count +
        newValueProp.count;
      stats.totalReplacements += ideaReplacements;
      stats.ideaTitleChanged = newTitle !== currentIdea.title;

      if (ideaReplacements > 0) {
        await tx.idea.update({
          where: { id: ideaId },
          data: {
            title: newTitle,
            description: newDesc.value,
            problem: newProblem.value,
            valueProposition: newValueProp.value,
          },
        });
        const ideaCount = newDesc.count + newProblem.count + newValueProp.count;
        if (ideaCount > 0) {
          stats.occurrencesByLocation.push({
            kind: "Idea",
            id: ideaId,
            count: ideaCount,
            title: "Idea · descripción",
          });
        }
      }
    }

    // 2) Project
    const currentProject = await tx.project.findUnique({
      where: { id: projectId },
      select: { name: true, description: true },
    });
    if (currentProject) {
      const newProjectName = cleanNew;
      const newProjectDesc = replaceAllWith(
        currentProject.description ?? "",
        cleanOld,
        cleanNew
      );
      const projectReplacements =
        (newProjectName !== currentProject.name ? 1 : 0) +
        newProjectDesc.count;
      stats.totalReplacements += projectReplacements;
      stats.projectNameChanged = newProjectName !== currentProject.name;

      if (projectReplacements > 0) {
        await tx.project.update({
          where: { id: projectId },
          data: {
            name: newProjectName,
            description:
              newProjectDesc.count > 0
                ? newProjectDesc.value
                : currentProject.description,
          },
        });
        if (newProjectDesc.count > 0) {
          stats.occurrencesByLocation.push({
            kind: "Project",
            id: projectId,
            count: newProjectDesc.count,
            title: "Project · descripción",
          });
        }
      }
    }

    // 3) ProjectPhases
    const phases = await tx.projectPhase.findMany({
      where: { projectId },
      select: {
        id: true,
        label: true,
        type: true,
        artifacts: true,
        questions: true,
        subStepArtifact: true,
      },
    });
    for (const phase of phases) {
      const updates: Prisma.ProjectPhaseUpdateInput = {};
      let phaseCount = 0;
      let phaseChanged = false;

      if (phase.artifacts != null) {
        const { value, count } = deepReplaceInJson(
          phase.artifacts,
          cleanOld,
          cleanNew
        );
        if (count > 0) {
          updates.artifacts = value as Prisma.InputJsonValue;
          phaseChanged = true;
          phaseCount += count;
        }
      }
      if (phase.questions != null) {
        const { value, count } = deepReplaceInJson(
          phase.questions,
          cleanOld,
          cleanNew
        );
        if (count > 0) {
          updates.questions = value as Prisma.InputJsonValue;
          phaseChanged = true;
          phaseCount += count;
        }
      }
      // Skip naming artifact for IDENTITY phase — contains the exact name
      // the user just chose, so replacing it would overwrite their selection.
      if (phase.subStepArtifact != null && phase.type !== "IDENTITY") {
        const { value, count } = deepReplaceInJson(
          phase.subStepArtifact,
          cleanOld,
          cleanNew
        );
        if (count > 0) {
          updates.subStepArtifact = value as Prisma.InputJsonValue;
          phaseChanged = true;
          phaseCount += count;
        }
      }

      if (phaseChanged) {
        await tx.projectPhase.update({
          where: { id: phase.id },
          data: updates,
        });
        stats.artifactsUpdated += 1;
        stats.totalReplacements += phaseCount;
        stats.occurrencesByLocation.push({
          kind: "ProjectPhase",
          id: phase.id,
          count: phaseCount,
          title: phase.label,
        });
      }
    }

    // 4) Reports
    const reports = await tx.report.findMany({
      where: { ideaId },
      select: {
        id: true,
        title: true,
        content: true,
        scorecard: true,
      },
    });
    for (const report of reports) {
      const newTitle = replaceAllWith(report.title, cleanOld, cleanNew);
      const newContent = replaceAllWith(report.content, cleanOld, cleanNew);
      const newScorecard =
        report.scorecard == null
          ? { value: report.scorecard, count: 0 }
          : replaceAllWith(report.scorecard, cleanOld, cleanNew);

      const total = newTitle.count + newContent.count + newScorecard.count;
      if (total > 0) {
        await tx.report.update({
          where: { id: report.id },
          data: {
            title: newTitle.value,
            content: newContent.value,
            scorecard:
              newScorecard.count > 0
                ? newScorecard.value
                : report.scorecard,
          },
        });
        stats.reportsUpdated += 1;
        stats.totalReplacements += total;
        stats.occurrencesByLocation.push({
          kind: "Report",
          id: report.id,
          count: total,
          title: report.title,
        });
      }
    }
  });

  return stats;
}

/**
 * Dry-run: estimates the number of occurrences of `oldName` across the
 * same set of locations that `propagateRename` would touch, WITHOUT
 * writing anything to the database. Used by the UI to show "this rename
 * would affect N mentions in M documents" before the user confirms.
 */
export interface PreviewStats {
  occurrencesByLocation: OccurrenceLocation[];
  totalReplacements: number;
  totalDocuments: number;
}

export async function previewRename(params: {
  ideaId: string;
  projectId: string;
  oldName: string;
}): Promise<PreviewStats> {
  const { ideaId, projectId, oldName } = params;
  const cleanOld = oldName.trim();

  if (!cleanOld || cleanOld.length < 2) {
    return {
      occurrencesByLocation: [],
      totalReplacements: 0,
      totalDocuments: 0,
    };
  }

  const occurrencesByLocation: OccurrenceLocation[] = [];
  let total = 0;

  // 1) Idea
  const idea = await prisma.idea.findUnique({
    where: { id: ideaId },
    select: { description: true, problem: true, valueProposition: true },
  });
  if (idea) {
    let count = 0;
    for (const field of [
      idea.description,
      idea.problem,
      idea.valueProposition,
    ] as Array<string | null>) {
      if (!field) continue;
      count += deepCountInJson(field, cleanOld);
    }
    if (count > 0) {
      total += count;
      occurrencesByLocation.push({
        kind: "Idea",
        id: ideaId,
        count,
        title: "Idea · descripción",
      });
    }
  }

  // 2) Project
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { description: true },
  });
  if (project?.description) {
    const count = deepCountInJson(project.description, cleanOld);
    if (count > 0) {
      total += count;
      occurrencesByLocation.push({
        kind: "Project",
        id: projectId,
        count,
        title: "Project · descripción",
      });
    }
  }

  // 3) ProjectPhases
  const phases = await prisma.projectPhase.findMany({
    where: { projectId },
    select: {
      id: true,
      label: true,
      type: true,
      artifacts: true,
      questions: true,
      subStepArtifact: true,
    },
  });
  for (const phase of phases) {
    let count = 0;
    for (const col of [phase.artifacts, phase.questions]) {
      if (col == null) continue;
      count += deepCountInJson(col, cleanOld);
    }
    // Skip naming artifact for IDENTITY phase — see propagateRename.
    if (phase.subStepArtifact != null && phase.type !== "IDENTITY") {
      count += deepCountInJson(phase.subStepArtifact, cleanOld);
    }
    if (count > 0) {
      total += count;
      occurrencesByLocation.push({
        kind: "ProjectPhase",
        id: phase.id,
        count,
        title: phase.label,
      });
    }
  }

  // 4) Reports
  const reports = await prisma.report.findMany({
    where: { ideaId },
    select: { id: true, title: true, content: true, scorecard: true },
  });
  for (const report of reports) {
    let count = 0;
    for (const col of [report.title, report.content, report.scorecard]) {
      if (!col) continue;
      count += deepCountInJson(col, cleanOld);
    }
    if (count > 0) {
      total += count;
      occurrencesByLocation.push({
        kind: "Report",
        id: report.id,
        count,
        title: report.title,
      });
    }
  }

  return {
    occurrencesByLocation,
    totalReplacements: total,
    totalDocuments: occurrencesByLocation.length,
  };
}
